general {
    lock_cmd         = hyprlock
    before_sleep_cmd = hyprlock
    grace            = 5
}

listener {
    timeout    = 270
    on-timeout = brightnessctl -s set 0
    on-resume  = brightnessctl -r
}

listener {
    timeout    = 300
    on-timeout = hyprlock
}

listener {
    timeout    = 600
    on-timeout = systemctl suspend
}